---
title: "Lab 01 - Hello R"
author: "AFRAH Jaber"
date: "1/2/2021"
output: html_document
---

University ID:2201002977 

### Load packages

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```
> summarise(datasaurus_dozen)
> head(datasaurus_dozen)
> View(datasaurus_dozen)

#answer for lab 1  (This package wraps the awesome Datasaurus Dozen dataset, which contains 13 sets of x-y data. Each sub-dataset has five statistics that are (almost) the same in each case. (These are the mean of x, mean of y, standard deviation of x, standard deviation of y, and Pearson correlation between x and y). However, scatter plots reveal that each sub-dataset looks very different. The dataset is intended to be used to teach students that it is important to plot their own datasets, rather than relying only on statistics.)

### Lab Exercise dino_data %>%summarize(r = cor(x, y))
# A tibble: 1 x 1
        r
    <dbl>
1 -0.0645
 
> star_data <-datasaurus_dozen %>%filter(dataset == "star")

> 
> ggplot(data = star_data, mapping = aes(x = x, y = y)) +geom_point()
> star_data %>%summarize(r = cor(x, y))
# A tibble: 1 x 1
        r
    <dbl>
1 -0.0630

  circle_data <-datasaurus_dozen %>%filter(dataset == "circle")
> 
>  ggplot(data = circle_data, mapping = aes(x = x, y = y)) +geom_point()
> 
> circle_data %>%summarize(r = cor(x, y))
# A tibble: 1 x 1
        r
    <dbl>
1 -0.0683
> 
> datasaurus_dozen %>% group_by(dataset) %>% summarize(r = cor(x, y)) %>% print(13)
# A tibble: 13 x 2
   dataset          r
 * <chr>        <dbl>
 1 away       -0.0641
 2 bullseye   -0.0686
 3 circle     -0.0683
 4 dino       -0.0645
 5 dots       -0.0603
 6 h_lines    -0.0617
 7 high_lines -0.0685
 8 slant_down -0.0690
 9 slant_up   -0.0686
10 star       -0.0630
11 v_lines    -0.0694
12 wide_lines -0.0666
13 x_shape    -0.0656

"Done with Lab 2” 

